version: "3"

services:
  postgres:
    image: "postgres:14.5"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: goplex
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
     - learning
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
  
  backend: 
    container_name: golang-api
    build:
      dockerfile: ./backend.Dockerfile
    ports: 
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - learning

  frontend:
    container_name: frontend-web
    build:
      dockerfile: ./frontend.Dockerfile
    ports:
        - "5173:5173"
    depends_on:
      - backend
      - postgres 
    networks:
     - learning 


networks:
  learning:
    driver: bridge
    


