apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: psql-test
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-05-20T16:53:56Z"
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: psql-test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 16.3.0
    helm.sh/chart: postgresql-15.3.3
  name: psql-test-postgresql
  namespace: default
  resourceVersion: "426387"
  uid: fac218df-8376-4f4e-9d77-9850a4d875aa
spec:
  clusterIP: 10.103.152.87
  clusterIPs:
  - 10.103.152.87
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-postgresql
    port: 5432
    protocol: TCP
    targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: psql-test
    app.kubernetes.io/name: postgresql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
