apiVersion: v1
kind: ConfigMap
metadata:
  name: create-tables-sql-config
data:
  create_tables.sql: |
    CREATE TABLE public.genres (
        id integer NOT NULL,
        genre character varying(255),
        created_at timestamp without time zone,
        updated_at timestamp without time zone
    );
