{{- if .Values.configmap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-app.fullname" . }}
  labels:
    {{- include "go-app.labels" . | nindent 4 }}
data: 
   {{- range $name, $config := .Values.configmap.values }}
  {{ $name }}: |
    {{ $config | indent 4 }}
  {{- end }}
{{- end }}
