apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: psql-test
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-05-21T16:40:44Z"
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: psql-test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 16.3.0
    helm.sh/chart: postgresql-15.3.3
  name: postgres
  namespace: default
  resourceVersion: "481569"
  uid: 4da652b5-8c37-4684-9bae-080fea92536c
spec:
  clusterIP: 10.99.117.253
  clusterIPs:
    - 10.99.117.253
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: tcp-postgresql
      port: 5432
      protocol: TCP
      targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: psql-test
    app.kubernetes.io/name: postgresql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
